# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 611)
        MainWindow.setWindowTitle("Colégio Principia")
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.copyright_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyright_label.sizePolicy().hasHeightForWidth())
        self.copyright_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.copyright_label.setFont(font)
        self.copyright_label.setText("")
        self.copyright_label.setObjectName("copyright_label")
        self.gridLayout.addWidget(self.copyright_label, 3, 0, 1, 1, QtCore.Qt.AlignBottom)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setText("")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout.addWidget(self.logo_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mensagem_label = QtWidgets.QLabel(self.centralwidget)
        self.mensagem_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mensagem_label.sizePolicy().hasHeightForWidth())
        self.mensagem_label.setSizePolicy(sizePolicy)
        self.mensagem_label.setMinimumSize(QtCore.QSize(0, 12))
        self.mensagem_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mensagem_label.setFont(font)
        self.mensagem_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.mensagem_label.setText("Usuário ou senha incorreta")
        self.mensagem_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mensagem_label.setObjectName("mensagem_label")
        self.gridLayout_4.addWidget(self.mensagem_label, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 12))
        self.label.setMaximumSize(QtCore.QSize(0, 12))
        self.label.setText("")
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 12))
        self.label_2.setMaximumSize(QtCore.QSize(0, 12))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(182)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(182, 32))
        self.login_btn.setMaximumSize(QtCore.QSize(182, 32))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.login_btn.setStyleSheet("")
        self.login_btn.setText("Entrar")
        self.login_btn.setObjectName("login_btn")
        self.gridLayout_3.addWidget(self.login_btn, 4, 0, 1, 2, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem4, 3, 0, 1, 2)
        self.password_txtfield = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(179)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(self.password_txtfield.sizePolicy().hasHeightForWidth())
        self.password_txtfield.setSizePolicy(sizePolicy)
        self.password_txtfield.setMinimumSize(QtCore.QSize(170, 21))
        self.password_txtfield.setMaximumSize(QtCore.QSize(170, 21))
        self.password_txtfield.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.password_txtfield.setMaxLength(70)
        self.password_txtfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_txtfield.setAlignment(QtCore.Qt.AlignCenter)
        self.password_txtfield.setPlaceholderText("Senha")
        self.password_txtfield.setObjectName("password_txtfield")
        self.gridLayout_3.addWidget(self.password_txtfield, 1, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.user_txtfield = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(179)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(self.user_txtfield.sizePolicy().hasHeightForWidth())
        self.user_txtfield.setSizePolicy(sizePolicy)
        self.user_txtfield.setMinimumSize(QtCore.QSize(170, 21))
        self.user_txtfield.setMaximumSize(QtCore.QSize(170, 21))
        self.user_txtfield.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.user_txtfield.setMaxLength(70)
        self.user_txtfield.setAlignment(QtCore.Qt.AlignCenter)
        self.user_txtfield.setPlaceholderText("Usuário")
        self.user_txtfield.setClearButtonEnabled(False)
        self.user_txtfield.setObjectName("user_txtfield")
        self.gridLayout_3.addWidget(self.user_txtfield, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.password_txtfield.returnPressed.connect(self.login_btn.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.user_txtfield, self.password_txtfield)
        MainWindow.setTabOrder(self.password_txtfield, self.login_btn)

    def retranslateUi(self, MainWindow):
        pass

